version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
jobs:
  buildbackend: ## build backend image
    description: build and push backend docker image to container registry
    machine: true
    steps:
      - checkout
      ## authorize with gcp service account key
      - run: cat .circleci/support-force-circleci.json | docker login -u _json_key --password-stdin https://gcr.io
      ## build the application image
      - run: docker build -f SupportForceBE/stagingbe.dockerfile --build-arg dockfoovars=${foo_vars} -t gcr.io/support-force/supportforcebe:latest .
      ## push the image to container registry
      - run: docker push gcr.io/support-force/supportforcebe:latest
  deploy: ## deploy frontend to gcp kubernetes engine
    description: deploy backend image to Google Kubernetes cluster
    machine: true
    steps:
      - checkout
      ## install `gcloud` and `kubectl` if not already installed
      - gcp-gke/install
      ## initialize the `gcloud` and `kubetcl` CLI
      # - gcp-gke/init
      - run: gcloud auth activate-service-account --key-file=.circleci/support-force-circleci.json
      - run: gcloud --quiet config set project support-force
      - run: gcloud --quiet config set compute/zone us-east4-a
      ## update a deployment docker image
      - run: gcloud container clusters get-credentials supportforce-cluster
      ## create supportforce-cluster deployment
      - run: kubectl apply -f SupportForceBE/.kubernetes_yaml/tomcat-backend-deployment.yaml
      ## update image
      - run: kubectl set image deployment --all backend=gcr.io/support-force/supportforcebe:latest
      ## create supportforce-cluster service
      - run: kubectl apply -f SupportForceBE/.kubernetes_yaml/tomcat-backend-service.yaml
workflows:
  buildbackend_deploy:
    jobs:
      - buildbackend
      - deploy:
          requires:
            - buildbackend
