version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
jobs:
  buildbackend: ## build backend image
    description: build and push backend docker image to container registry
    machine: true
    steps:
      - checkout
      ## build the application image
      - run: docker build -f SupportForceBE/stagingbe.dockerfile --build-arg DB_PASSWORD=${DB_PASSWORD} -t gcr.io/support-force/supportforcebe:latest .
      ## push the image to container registry
      - run: docker push gcr.io/support-force/supportforcebe:latest
  deploy: ## deploy frontend to gcp kubernetes engine
    description: deploy backend image to Google Kubernetes cluster
    machine: true
    steps:
      ## install `gcloud` and `kubectl` if not already installed
      - gcp-gke/install
      ## initialize the `gcloud` CLI
      - gcp-gke/init
      ## update a deployment docker image
      - run: gcloud container clusters get-credentials supportforce-cluster
      ## create supportforce-cluster deployment
      - run: kubectl apply -f .kubernetes_yaml/tomcat-backend-deployment.yaml
      ## create supportforce-cluster service
      - run: kubectl apply -f .kubernetes_yaml/tomcat-backend-service.yaml
workflows:
  build_update_deploy:
    jobs:
      - buildbackend
      - deploy:
          requires:
            - buildbackend
