---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tomcat-backend"
  namespace: "backend"
  labels:
    app: "tomcat-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "tomcat-backend"
  template:
    metadata:
      labels:
        app: "tomcat-backend"
    spec:
      containers:
      - name: "tomcat-backend-containers"
        image: "gcr.io/support-force/supportforcebe:latest"
        env:
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "uat-db-secret"
                key: "foopa"
---
## autoscaler is not needed in staging, but it works for production
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tomcat-backend-hpa"
  namespace: "backend"
  labels:
    app: "tomcat-backend-hpa"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tomcat-backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
