---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "tomcat-backend-config"
  namespace: "backend"
  labels:
    app: "tomcat-backend"
data:
  DB_USERNAME: "postgres"
  DB_URL: "jdbc:postgresql://35.236.247.30:5432/postgres"
  DB_PASSWORD: "OrCbp5r8HxIxcPkK"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tomcat-backend"
  namespace: "backend"
  labels:
    app: "tomcat-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "tomcat-backend"
  template:
    metadata:
      labels:
        app: "tomcat-backend"
    spec:
      containers:
      - name: "supportforcebe-sha256"
        image: "gcr.io/support-force/supportforcebe@sha256:ad2fe39751c0911d394b48bc062d00a2e25fa54ab02138e7cc0b45d6ec3a145d"
        env:
        - name: "DB_USERNAME"
          valueFrom:
            configMapKeyRef:
              key: "DB_USERNAME"
              name: "tomcat-backend-config"
        - name: "DB_URL"
          valueFrom:
            configMapKeyRef:
              key: "DB_URL"
              name: "tomcat-backend-config"
        - name: "DB_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "DB_PASSWORD"
              name: "tomcat-backend-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tomcat-backend-hpa"
  namespace: "backend"
  labels:
    app: "tomcat-backend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tomcat-backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
