---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tomcat-backend"
  namespace: "backend"
  labels:
    app: "tomcat-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "tomcat-backend"
  template:
    metadata:
      labels:
        app: "tomcat-backend"
    spec:
      containers:
      - name: "uat-supportforcebe-sha256"
        image: "gcr.io/support-force/uat-supportforcebe:latest"
        ports:
        - containerPort: 80
        - containerPort: 8080
        env:
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: "uat-db-secret"
                key: "foopa"
          - name: "DB_USERNAME"
            valueFrom:
              secretKeyRef:
                name: "uat-db-secret"
                key: "fooser"
      - name: "cloudsql-proxy"
        image: "gcr.io/cloudsql-docker/gce-proxy:1.14"
        command: [
          "/cloud_sql_proxy",
          "-instances=uat-db-01=tcp:3306",
          # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
          # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
          # "-ip_address_types=PRIVATE",
          "-credential_file=/secrets/cloudsql/credentials.json"
        ]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: "uat-db-secret"
            mountPath: "/secrets/cloudsql"
            readOnly: true
      volumes:
      - name: "uat-db-secret"
        secret:
          secretName: "uat-db-secret"
          items:
            - key: "fooser"
              path: "username"
            - key: "foopa"
              path: "password"
---
## autoscaler is not needed in staging, but it works for production
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "tomcat-backend-hpa"
  namespace: "backend"
  labels:
    app: "tomcat-backend-hpa"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "tomcat-backend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
